server:
  port: 8080

spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always

app:
  secret: ${TODO_SECRET}
  cors:
    origin: ${CORS_ORIGIN}
  publicPaths: /actuator/health, /api/auth/**
